- name: Register RHN
  hosts: db1.rhpds.opentlc.com
  tasks:
     - name: List All repositories
       redhat_repositories:
         state: present
         username: "{{ rhn_username }}"
         password: "{{ rhn_password }}"
         list=all
